apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: default
  labels:
    app: spring-label   # ← مهم جدًا
spec:
  selector:
    app: spring-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
